# -*- coding: utf-8 -*-
{
    'name': 'Employee Extra',
    'version': '0.1',
    'summary': 'Extend employee records with additional attributes and features.',
    'description': """
This module extends employee records with new features such as job, cost centers, education, and termination data.
It enhances HR operations with detailed employee profiles and advanced data management capabilities.
Key Features:
- Manage job and department layers
- Track employee education, training, and achievements
- Add employee warnings, contacts, and documents
- Extend the termination process with additional data fields
    """,
    'author': 'TORAHOPER',
    'website': 'https://torahoper.ir',
    'license': 'LGPL-3',
    'category': 'Human Resources',
    'depends': [
        'hr',
        'web_hierarchy',
        'base',
        'hr_org_chart',
        'hr_contract',
    ],
    'data': [
        'security/hr_security.xml',
        'security/ir.model.access.csv',
        'views/hr_job_views.xml',
        'views/hr_tamin_job_views.xml',
        'views/hr_cost_center_views.xml',
        'views/hr_employee_cost_center_views.xml',
        'views/hr_employee_public_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_termination_type_views.xml',
        'views/hr_relationship_type_views.xml',
        'views/hr_document_type_views.xml',
        'views/hr_employee_termination_views.xml',
        'views/hr_employee_dependent_views.xml',
        'views/hr_employee_document_views.xml',
        'views/hr_employee_education_views.xml',
        'views/hr_employee_training_views.xml',
        'views/hr_employee_warning_letter_views.xml',
        'views/hr_employee_payment_type.xml',
        'views/hr_employee_contact.xml',
        'views/hr_employee_contact_category.xml',
        'views/hr_employee_achievement.xml',
        'views/res_company_views.xml',
        'views/hr_department_layer_views.xml',
        'views/hr_department_views.xml',
        'views/hr_job_tier_views.xml',
        'views/hr_job_level_views.xml',
        'views/hr_work_location_views.xml',
        'views/res_partner_view.xml',
        'views/res_users_views.xml',
        'views/hr_religion_views.xml',
        'views/hr_station_deposit_views.xml',
        'views/hr_station_rent_views.xml',
        'views/hr_ext_menu.xml',
        'data/hr_personnel_code_sequence.xml',
        'data/hr_job_tier_data.xml',
        'data/hr_document_type_data.xml',
        'wizard/hr_departure_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'employee_ext/static/src/**/*',
        ],
    },
    'images': [],
    'external_dependencies': {},
    'installable': True,
    'application': True,
    'auto_install': False,
    'price': 0.0,
    'currency': '',
    'live_test_url': '',
    'pre_init_hook': '',
    'post_init_hook': '',
    'uninstall_hook': '',
    'sequence': 0,
    'icon': '',
    'bootstrap': False,
}
