# -*- coding: utf-8 -*-
{
    'name': 'Odoo Mail Inbox',
    'version': '1.1.0',
    'category': 'Productivity',
    'author': 'Daric',
    'website': "https://daric-saas.ir",
    'license': 'OPL-1',
    'summary': 'Odoo Mail Inbox',
    'description': """Mail Inbox for Odoo""",
    'depends': ['base', 'mail', 'web'],
    'data': [
        'data/ir_cron_data.xml',
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'wizard/email_compose_wizard.xml',
        'views/mail_inbox_views.xml',
        'views/webclient_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'web/static/lib/select2/select2.css',
            'web/static/lib/select2-bootstrap-css/select2-bootstrap.css',
            'web/static/lib/select2/select2.js',
            'is_mail_inbox/static/src/css/*.css',
            'is_mail_inbox/static/src/scss/*.scss',
            'is_mail_inbox/static/lib/ckeditor-super.js',
            'is_mail_inbox/static/src/components/mail_inbox/*.js',
            'is_mail_inbox/static/src/components/mail_inbox/*.xml',
            'is_mail_inbox/static/src/components/mail_inbox/*.xml',
        ],
    },
    'images': ['static/description/main_screenshot.jpg'],
    'application': True,
    'installable': True,
    'auto_install': False,
    'currency': 'EUR',
    'price': 99,
}
