from . import mailchimp_lists
from . import mailchimp_accounts
from . import mass_mailing_contact
from . import mass_mailing_list
from . import mailchimp_template
from . import mass_mailing
from . import mailing_contact_subscription
from . import res_partner
from . import res_partner_category
from . import mailchimp_segments
from . import mailchimp_merge_fields
from . import mailchimp_queue_process
from . import link_tracker
from . import mailchimp_log
